services:
  - type: web
    name: stock-options-tool-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && PYTHONPATH=/opt/render/project/src gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PRODUCTION
        value: true
      - key: PORT
        value: 8080
